<a href="https://colab.research.google.com/github/jibintom/Machine-Learning-Codebasics-/blob/main/a15.%20Hyper%20parameter%20Tuning%20(GridSearchCV)/Hyper_parameter_Tuning_on_load_digits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.datasets import load_digits
digits=load_digits()

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [7]:
df=pd.DataFrame(digits.data)
df["target"]=digits.target
df["target_name"]=df.target.apply(lambda x:digits.target_names[x])
df.head()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,target,target_name
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4,4

In [33]:
model_para=({
    "LogisticRegression": {
        "model": LogisticRegression(solver="liblinear", multi_class="auto"),
        "para": {
            "C": [5,10,20]  
          } 
        },
        "RandomForestClassifier": {
            "model": RandomForestClassifier(),
            "para": {
                "n_estimators": [5,10,20],
                "criterion": ["gini","entropy","log_loss"]
              }
            },
            "SVC": {
                "model": SVC(gamma="auto"),
                "para": {
                    "C": [1,10,20],
                    "kernel": ["linear","poly","rbf","sigmoid"]
                  }
                },
                "MultinomialNB": {
                    "model": MultinomialNB(),
                    "para": {
                        "alpha": [0,1]
                      }
                    },
                    "GaussianNB": {
                        "model": GaussianNB(),
                        "para": { }
                    },
                        "DecisionTreeClassifier": {
                            "model": DecisionTreeClassifier(),
                            "para": {
                                "criterion": ["gini","entropy","log_loss"]
                            }
                        }         
})

In [34]:
scores= []

from sklearn.model_selection import GridSearchCV
for model_name, mp in model_para.items():
  gscv=GridSearchCV(mp["model"], mp["para"], cv=5, return_train_score=False)
  gscv.fit(digits.data, digits.target)
  scores.append({
      "model name": model_name,
      "best score": gscv.best_score_,
      "best parameter": gscv.best_params_
  })

df=pd.DataFrame(scores, columns=["model name","best score","best parameter"])
df

,model name,best score,best parameter
0,LogisticRegression,0.918223,{'C': 10}
1,RandomForestClassifier,0.919335,"{'criterion': 'entropy', 'n_estimators': 20}"
2,SVC,0.968842,"{'C': 1, 'kernel': 'poly'}"
3,MultinomialNB,0.870350,{'alpha': 0}
4,GaussianNB,0.806928,{}
5,DecisionTreeClassifier,0.806374,{'criterion': 'entropy'}

In [35]:
from sklearn.datasets import load_wine
wine=load_wine()

In [36]:
df=pd.DataFrame(wine.data)
df["target"]=wine.target
df["target_name"]=df.target.apply(lambda x:wine.target_names[x])
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,target,target_name
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0,class_0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0,class_0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0,class_0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0,class_0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0,class_0

In [39]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    },
    'naive_bayes_gaussian': {
        'model': GaussianNB(),
        'params': {}
    },
    'naive_bayes_multinomial': {
        'model': MultinomialNB(),
        'params': {}
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini','entropy'],
            
        }
    }     
}

In [40]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(wine.data, wine.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                     model  best_score                   best_params
0                      svm    0.961111  {'C': 1, 'kernel': 'linear'}
1            random_forest    0.972222          {'n_estimators': 10}
2      logistic_regression    0.961111                      {'C': 1}
3     naive_bayes_gaussian    0.966349                            {}
4  naive_bayes_multinomial    0.843968                            {}
5            decision_tree    0.904762      {'criterion': 'entropy'}